### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by JanOsusky** [NhatAnh1708/TFLITE-Yolov9#4]
Hello, 

I would like to ask under what conditions can this converted YOLOv9 model can be used from the license point of view. I would like to use it in a mobile app, but the app can only use open-source projects under licenses like MIT or Apache 2.0 to get approved for publishing in app store. This repository is under Apache 2.0, but the implementation of the model itself is under GPL 3.0 which doesn't allow use in mobile apps this way.  I wonder what is the legal status of this way converted model.
Thank you for answers

**Comment by NhatAnh1708** [comment]
I'm sorry about that, I changed the LICENSE from apache 2.0 to GPL 3.0 because i used the pretrained model from GPL 3.0 LICENSE. You can retrained the model and converted it using the repo to use for commercial
Thanks for issues
